apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  BACKEND_URL: {{ .Values.configMap.backendUrl | quote }}
  NODE_ENV: {{ .Values.configMap.nodeEnv | quote }}