apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGODB_URL: {{ .Values.mongodb.url | quote }}
  NODE_ENV: {{ .Values.nodeEnv | quote }}