apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secret.apiKey }}
  MONGODB_PASSWORD: {{ .Values.mongodb.pass }}